package com.abdu.msgsharingapp

data class Hobby(var title: String)

object HobbiesSupplier {

    val hobbies = listOf(
        Hobby("Running"),
        Hobby("Swimming"),
        Hobby("Movies"),
        Hobby("Ping pong"),
        Hobby("Eating"),
        Hobby("Traveling"),
        Hobby("Skydiving"),
        Hobby("BungeeJumping"),
        Hobby("Soccer"),
        Hobby("VideoGames"),
        Hobby("Pranks"),
        Hobby("Dancing"),
        Hobby("Talking"),
        Hobby("Coding"),
        Hobby("Tennis"),
        Hobby("Fishing"),
        Hobby("Wakeboarding"),
        Hobby("Skating"),
        Hobby("Skiing"),
        Hobby("Triathlons"),
        Hobby("Aquathlons"),
        Hobby("Duathlons"),
        Hobby("Hiking"),
        Hobby("Ultra marathons"),
        Hobby("Floor hockey"),
        Hobby("Acting"),
        Hobby("Running"),
        Hobby("Swimming"),
        Hobby("Movies"),
        Hobby("Ping pong"),
        Hobby("Eating"),
        Hobby("Traveling"),
        Hobby("Skydiving"),
        Hobby("BungeeJumping"),
        Hobby("Soccer"),
        Hobby("VideoGames"),
        Hobby("Pranks"),
        Hobby("Dancing"),
        Hobby("Talking"),
        Hobby("Coding"),
        Hobby("Tennis"),
        Hobby("Fishing"),
        Hobby("Wakeboarding"),
        Hobby("Skating"),
        Hobby("Skiing"),
        Hobby("Triathlons"),
        Hobby("Aquathlons"),
        Hobby("Duathlons"),
        Hobby("Hiking"),
        Hobby("Ultra marathons"),
        Hobby("Floor hockey"),
        Hobby("Acting")
    )
}